### ISSUE TITLE
Not Working on intel x64 laptop

### ISSUE THREAD

**Issue by Master-Mind-Robotics** [thebookisclosed/AmperageKit#10]
I'm not an expert so forgive me if its not meant to work but i get the message saying I can't run it on my laptop

**Comment by awarson2233** [comment]
Recall haven't support x64 yet

**Comment by thebookisclosed** [comment]
Yeah, the second line of the Readme says
> At the moment, Amperage can only enable recall if your machine has an Arm64 CPU / SoC. That is, any Qualcomm Snapdragon, Microsoft SQ, or Ampere chipset.
