### ISSUE TITLE
No support for intel processors

### ISSUE THREAD

**Issue by daanvancamp** [thebookisclosed/AmperageKit#11]

**Comment by mollyvita** [comment]
you should check readme

**Comment by daanvancamp** [comment]
> you should check readme

It is a suggestion rather than an issue.

**Comment by daanvancamp** [comment]
The code could be extended in my opinion.

**Comment by mollyvita** [comment]
> It is a suggestion rather than an issue.

there's no AI components for x86_64 arch, now you can just wait. the dev knows about this, they will fix it when there will be an actual possibility to do so

**Comment by thebookisclosed** [comment]
> It is a suggestion rather than an issue.

Well then why are you filing it as an issue? Like riivx said, this is not a priority at the moment. The code is rather flexible as is, requiring very minimal changes to add x86_64 support once the packages drop.

**Comment by Elaman0117** [comment]
Any idea we have?

**Comment by mollyvita** [comment]
@Elaman0117 
> Most x86_64 users will have to wait until Microsoft publishes AI Components for their platform.

**Comment by Elaman0117** [comment]
> @Elaman0117
> 
> > Most x86_64 users will have to wait until Microsoft publishes AI Components for their platform.

I thought 24H2 CC has already done it, for chips like HX370...
