### ISSUE TITLE
Does not detect NPU on Qualcomm Dev Kit

### ISSUE THREAD

**Issue by fsfc1** [thebookisclosed/AmperageKit#13]
Running this on the new Qualcomm Dev Kit for Windows does not detect the NPU

**Comment by gus33000** [comment]
You should not have to use this tool on that device anyway; it meets Recall System requirements by using an X Elite SoC and having the right amount of ram and storage.

Just make sure you are using a compatible OS build; learn more at https://aka.ms/wip-dev-11-22
