### ISSUE TITLE
Newer version

### ISSUE THREAD

**Issue by almodovaris** [thebookisclosed/AmperageKit#16]
I'd say breath new life into it. It's doable. I have a Microsoft Volterra and it partly works: I got the prompt at login to enable Recall, but then it was nowhere available. I have Windows 26120.2702.

**Comment by thebookisclosed** [comment]
"Doable" is doing some real heavy lifting here, it's much more cumbersome to alter the results of the checks now.
https://github.com/thebookisclosed/AmperageKit/issues/14#issuecomment-2494604916
