### ISSUE TITLE
Request for x64 Support

### ISSUE THREAD

**Issue by RaulKong898** [thebookisclosed/AmperageKit#3]
Hi,

Please add support for Intel and AMD processors with x64 architecture. I'm sure you will add this support in the future, and I hope it will be as soon as possible.

Thank you!

**Comment by RTFTR** [comment]
Did you even read the Readme.md

It's for ARM64 architectures which don't support recall support

**Comment by RaulKong898** [comment]
Yes, I know this, but I want you to make it also for intel and amd processors on x64 architecture.

**Comment by RaulKong898** [comment]
> Did you even read the Readme.md
> 
> It's for ARM64 architectures which don't support recall support
Yes, I know this, but I want you to make it also for intel and amd processors on x64 architecture

**Comment by RaulKong898** [comment]
Yes, I know this, but I want you to make it also for intel and amd processors on x64 architecture

**Comment by RTFTR** [comment]
Dude, Recall feature is for arm64, not amd64
Modifying that is literally impossible

**Comment by thebookisclosed** [comment]
Hey @RaulKong898 
You've tagged me on Twitter like 4 times in the span of an hour, sent me half a dozen DMs in a similar rapid fire fashion, and now made an issue about something I already said is planned but can't influence the timeline of. Please knock it off.
