### ISSUE TITLE
Works great on Azure free tier

### ISSUE THREAD

**Issue by dfeldman** [thebookisclosed/AmperageKit#4]
This tool works on a basic Azure VM. Using an ARM64 VM, size E2pds (2 vCPU, 16 GB RAM), source image win11-24h2-pro. Just have to run Windows Update and reboot first. On this machine, Recall is a bit slow, but works fine. It's very easy to set up, thank you.

**Comment by pl4nty** [comment]
Do you know if it needs 16GB RAM/256GB disk like the public requirements? I didn't mention a SKU when adding to the README in #1, because I hadn't tested

**Comment by dfeldman** [comment]
I do not know. They do seem to have some very small ARM instances like Dplsv5 with 4GB, but I didn't try that.

**Comment by Marshall-Hallenbeck** [comment]
> Do you know if it needs 16GB RAM/256GB disk like the public requirements? I didn't mention a SKU when adding to the README in #1, because I hadn't tested

No, I'm using 8GB RAM and it works.

**Comment by ukhal** [comment]
> This tool works on a basic Azure VM. Using an ARM64 VM, size E2pds (2 vCPU, 16 GB RAM), source image win11-24h2-pro. Just have to run Windows Update and reboot first. On this machine, Recall is a bit slow, but works fine. It's very easy to set up, thank you.

Did you have to do anything else? I've tried to run a VM exactly like you describe, I set it up, update, reboot and then run the AmperageKit tool and it tells me that the version I'm using isnt supported,

**Comment by yusufipk** [comment]
> > This tool works on a basic Azure VM. Using an ARM64 VM, size E2pds (2 vCPU, 16 GB RAM), source image win11-24h2-pro. Just have to run Windows Update and reboot first. On this machine, Recall is a bit slow, but works fine. It's very easy to set up, thank you.
> 
> Did you have to do anything else? I've tried to run a VM exactly like you describe, I set it up, update, reboot and then run the AmperageKit tool and it tells me that the version I'm using isnt supported,

It doesn't work anymore because they pulled the update. https://x.com/_JohnHammond/status/1799350383506313671
